services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 2s
      retries: 5

  veggies:
    image: localhost/QuarkusVeggieService:native
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/demo
      - DATABASE_USER=demo
      - DATABASE_PASSWORD=demo
      - SUPERHERO_URL=https://quarkus-superhero.icyforest-1789839e.japaneast.azurecontainerapps.io
      - APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=e6b68f56-3dea-4789-acb2-a1ffa1aacfc4;IngestionEndpoint=https://japaneast-1.in.applicationinsights.azure.com/;LiveEndpoint=https://japaneast.livediagnostics.monitor.azure.com/;ApplicationId=30235274-26b7-43e0-8378-75cf1374978d
    depends_on:
      db:
        condition: service_healthy

